### ISSUE TITLE
Display content of a Caom object

### ISSUE THREAD

**Issue by andamian** [opencadc/caom2tools#38]
The __repr__ method in CaomObject uses the arg list of the class constructor to display the content of an object. Some classes, such Energy, do not have args in the constructor, hence nothing is displayed as the content.

I think that __repr__ should use the obeject __dict__ to find all the attributes.

To be consistent with the other classes, the ctor of Energy class should also accept arguments.

**Comment by ijiraq** [comment]
repr is supposed to show you how you would call the Class to build the current instance.  So, if the _init_ doesn't take arguments then repr should not show any.


Return a string containing a printable representation of an object. For many types, this function makes an attempt to return a string that would yield an object with the same value when passed to eval()<https://docs.python.org/3/library/functions.html#eval>, otherwise the representation is a string enclosed in angle brackets that contains the name of the type of the object together with additional information often including the name and address of the object. A class can control what this function returns for its instances by defining a __repr__()<https://docs.python.org/3/reference/datamodel.html#object.__repr__> method.


JJ

**Comment by andamian** [comment]
The fact that Energy's constructor takes no arguments is a bug.

The utility of __repr__ to reconstruct the object is questionable since Caom2 entities have extra fields that are not passed in the constructor (uuid, lastMod, checksum etc) so eval will build a different instance. IMO, for debugging purposes, __str__ should display all the attributes. Note: that __str__ in a list calls __repr__ on the members!
